version: '3.8'

services:
  web:
    build:
      context: ./ClickerWeb 
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - web
    restart: always
